name: Actualizar EPG Diariamente

on:
  schedule:
    - cron: '0 */12 * * *' # Se ejecuta cada 12 horas
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de EPG
        run: python update_epg.py

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "EPG Bot"
          git config --global user.email "bot@github.com"
          git add guia_completa.xml guia_completa.xml.gz
          git commit -m "Actualización automática de EPG" || exit 0
          git push
