  - name: Ejecutar Descarga
        run: python descargar.py

      - name: Ejecutar Procesamiento
        run: python procesar.py

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "EPG Bot"
          git config --global user.email "bot@github.com"
          git add guia_completa.xml
          git commit -m "Actualización EPG" || exit 0
          git push

          git config --global user.email "bot@github.com"
          git add guia_completa.xml guia_completa.xml.gz
          git commit -m "Actualización automática de EPG" || exit 0
          git push

