 name: Actualizar EPG

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar
        run: pip install requests

      - name: Script
        run: python update_epg.py

      - name: Push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add .
          git commit -m "update" || exit 0
          git push

